name: Deploy iOS to Firebase & App Store

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Ruby for Fastlane
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Decode and Install Apple Certificate
      - name: Decode and Install Apple Certificate
        env:
          IOS_DISTRIBUTION_CERT: ${{ secrets.IOS_DISTRIBUTION_CERT }}
          IOS_DISTRIBUTION_CERT_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERT_PASSWORD }}
        run: |
          echo "$IOS_DISTRIBUTION_CERT" | base64 --decode > ios_certificate.p12
          security create-keychain -p "temp" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "temp" build.keychain
          security import ios_certificate.p12 -k build.keychain -P "$IOS_DISTRIBUTION_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -k "temp" build.keychain

      # Decode and Install Provisioning Profile
      - name: Decode and Install Provisioning Profile
        env:
          IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > ios_profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios_profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Decode App Store Connect API Key
      - name: Decode App Store Connect API Key
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          mkdir -p fastlane
          echo "$APP_STORE_CONNECT_API_KEY" | base64 --decode > fastlane/AuthKey_${APP_STORE_CONNECT_KEY_ID}.p8

      # Build and Sign Flutter IPA
      - name: Build and Sign Flutter IPA
        run: flutter build ipa

      # Deploy IPA to Firebase App Distribution
      - name: Deploy IPA to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/ios/ipa/*.ipa \
          --app "1:36597009887:ios:1f2605c8364b9e9153486a" \
          --token ${{ secrets.FIREBASE_TOKEN }}
