name: Deploy to Firebase Hosting and APK/AAB on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Java version (Java 11, for example)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2

      # Decode Keystore from GitHub Secrets and store it in the correct path
      - name: Decode Keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo "$ANDROID_KEYSTORE" | base64 --decode > android/app/college-finder.jks

      # Create key.properties file
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=college-finder.jks" >> android/key.properties

      # Get the latest version code from a file or Git commit and increment it
      - name: Auto-increment version code
        id: versioning
        run: |
          VERSION_CODE=$(grep versionCode android/app/build.gradle | awk '{print $2}' | sed 's/[^0-9]*//g')
          VERSION_CODE=$((VERSION_CODE + 1))
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV
          VERSION_NAME="1.0.${VERSION_CODE}"
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      # Update versionCode and versionName in build.gradle
      - name: Update versionCode and versionName in build.gradle
        run: |
          sed -i "s/versionCode [0-9]\+/versionCode ${{ env.VERSION_CODE }}/g" android/app/build.gradle
          sed -i "s/versionName \"[^\"]*\"/versionName \"${{ env.VERSION_NAME }}\"/g" android/app/build.gradle

      # Build Flutter web
      - name: Build Flutter web
        run: flutter build web

      # Build Flutter APK (now it will be signed)
      - name: Build Flutter APK
        run: flutter build apk --release

      # Build Flutter AAB (signed)
      - name: Build Flutter AAB
        run: flutter build appbundle --release

      # Deploy Flutter web to Firebase Hosting
      - name: Deploying Web to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLEGE_FINDER_54F2C }}
          channelId: live
          projectId: college-finder-54f2c

      # Install Firebase CLI to deploy APK and AAB
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      # Deploy APK to Firebase App Distribution
      - name: Deploying APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app "1:36597009887:android:0fec54d9bc8e280453486a" \
          --token ${{ secrets.FIREBASE_TOKEN }}

      # Deploy AAB to Firebase App Distribution
      - name: Deploying AAB to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab \
          --app "1:36597009887:android:0fec54d9bc8e280453486a" \
          --token ${{ secrets.FIREBASE_TOKEN }}
